### ISSUE TITLE
Debug serial log output forgotten to disable for C3

### ISSUE THREAD

**Issue by Jason2866** [espressif/esp-phy-lib#3]
The serial console spits out this messages
```
chan:1,max_power:68
chan:2,max_power:68
chan:3,max_power:68
chan:4,max_power:68
chan:5,max_power:68
chan:6,max_power:68
chan:7,max_power:68
chan:8,max_power:68
chan:9,max_power:68
chan:10,max_power:68
chan:11,max_power:68
chan:12,max_power:68
chan:13,max_power:68
chan:14,max_power:68
```
Patched file which silenced the jabber.
[libphy.a.zip](https://github.com/espressif/esp-phy-lib/files/7804183/libphy.a.zip)

**Comment by igrr** [comment]
@Jason2866 thanks for reporting, this is now fixed in `master` branch of esp-idf, will be backported to release/v4.4 soon.
